# Generated by Django 4.1.6 on 2023-02-11 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=264)),
                ('bus_number', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_name', models.CharField(max_length=264)),
                ('route_number', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='TimeAssignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('from_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='bus',
            field=models.ManyToManyField(related_name='route', through='bus.TimeAssignModel', to='bus.bus'),
        ),
    ]
