# Generated by Django 4.1.6 on 2023-02-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_name',
            new_name='route',
        ),
    ]
