# Generated by Django 4.1.6 on 2023-02-11 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_rename_route_name_route_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='bus',
            field=models.ManyToManyField(related_name='routes', through='bus.TimeAssignModel', to='bus.bus'),
        ),
    ]
